### ISSUE TITLE
Is there a way to modify OutputPath from an inline task in csproj file?

### ISSUE THREAD

**Issue by am11** [jeffkl/MSBuild-NetCore#2]
✔️ When `Microsoft.Common.CurrentVersion.targets` is (automatically) included by MSBuild at the beginning of build, it validates the `OutputPath` properties via `_CheckForInvalidConfigurationAndPlatform` target, sets a local variable `OutDir` and continues to `CoreBuild` and friends. If validation fails (`OutputPath` property hasn't been *statically* defined), it fails with error or continues with Warning when `SkipInvalidConfigurations` is set. 

✔️ If we have `OutpuatPath` defined in an conditional scope, that also works as it can be evaluated statically (the default csproj template, e.g. under `Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCpu'"`).

✔️ If we have `OutputPath` defined in global scope (unconditioned), and we override the `OutputPath` in a conditional scope, the overridden value would be considered if and only if it is statically defined.

❗️ If we try to define the `OutputPath` property from inline task / external imported targets with `BuildDependsOn` calling the custom target to invoke the inline task for example, `_CheckForInvalidConfigurationAndPlatform` gives error as it cannot *see* the `OutputPath` prop statically defined anywhere.. 

❗️ Similarly, if we try to override the value of already defined `OutputPath` from an inline task, only statically defined value of `OutputPath` is captured in `OutDir`, then *after* this value is set, the overridden value from task/targets is considered but does not effect the corebuild of the *current* Build target and hence defeats the purpose. If we subsequently call another MSbuild task (for example to compile some external vcxproj from a csproj) and pass `OutputPath` as msbuild property, it uses the correct overridden value computed by the inline task.

Question:  Is there any way we can set `OutputPath` in csproj file in a *deferred* mode?

Not really an un-google-able question, but over the course of years people have asked the same:
* https://social.msdn.microsoft.com/Forums/vstudio/en-US/e70f06e8-9c02-43d0-8252-77cdc4afdcfc/property-scope-and-evaluation-order?forum=msbuild
* http://stackoverflow.com/q/13194336

The closest solution I have found is dynamically writing `VisualStudioPropertySheet`: http://stackoverflow.com/q/4249221, but not sure if that's is an overkill.

If it is possible, It would be a huge help if you could shed light on this. :)

**Comment by jeffkl** [comment]
You might be able to have your target run before `_CheckForInvalidConfigurationAndPlatform`

```xml
<Target Name="SetOutputPath" BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
  <OutputPath>foo\bar</OutputPath>
</Target>
```

OutputPath might be used before targets run so you might need to set it and re-set any properties that have already been set with its value.

**Comment by am11** [comment]
@jeffkl, thanks. Even when we set the property before the validation target, it doesn't get respected.

Seems like the issue is with the sequence of execution. [`Microsoft.Common.CurrentVersion.targets`](https://github.com/Microsoft/msbuild/blob/dc4906f/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets) captures OutputPath and set to the local property `OutDir`. It has `TreatAsLocalProperty="OutDir"`.

I have created a file called `OutputPathTest.csproj` for self contained repro with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <OutputPath>bin\UnwantedPath</OutputPath>
  </PropertyGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />

  <UsingTask TaskName="SomeCalculatedPath" TaskFactory="CodeTaskFactory"
             AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <MagicName ParameterType="System.String" Output="true" />
    </ParameterGroup>
    <Task>
      <Using Namespace="System.Reflection" />
      <Code Type="Fragment" Language="cs"><![CDATA[
          MagicName = "bin\\" + Guid.NewGuid().ToString("N").Substring(0, 15);
        ]]></Code>
    </Task>
  </UsingTask>

  <Target Name="GetSomeCalculatedPath">
    <SomeCalculatedPath>
      <Output TaskParameter="MagicName" PropertyName="OutputPath" />
    </SomeCalculatedPath>
  </Target>

  <Target Name="BeforeBuild"
          DependsOnTargets="_CheckForInvalidConfigurationAndPlatform;GetSomeCalculatedPath">
    <Message Importance="High" Text="OutputPath before build was: $(OutputPath)" />
  </Target>

  <Target Name="AfterBuild">
    <Message Importance="High" Text="OutputPath after build was: $(OutputPath)" />
  </Target>
</Project>
```


Running `msbuild OutputPathTest.csproj` yields:

```cmd
BeforeBuild:
  OutputPath before build was: bin\ea67c6ec490247c
PrepareForBuild:
  Creating directory "bin\UnwantedPath\".
  Creating directory "obj\Debug\".
...
...
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\OutputPathTest.dll" to "bin\UnwantedPath\OutputPathTest.dll".
  OutputPathTest -> C:\temp\msbuild-testing\bin\UnwantedPath\OutputPathTest.dll
  Copying file from "obj\Debug\OutputPathTest.pdb" to "bin\UnwantedPath\OutputPathTest.pdb".
AfterBuild:
  OutputPath after build was: bin\ea67c6ec490247c
```

Note that while Before and After build are setting correctly, OutputPath does not get overridden and therefore, `OutputPathTest.dll` lands in `bin\UnwantedPath`.

**Comment by am11** [comment]
@jeffkl, if overriding `OutputPath` from an inline task is not possible, would it make sense to request it as a feature in MSBuild repo (at the risk of getting rejected)? :)

**Comment by jeffkl** [comment]
I think your target ordering is wrong.  `BeforeBuild` needs to run _before_ `_CheckForInvalidConfigurationAndPlatform`.  `DependsOn` makes this target run after it.

Other properties also use the value of $(OutputPath) like $(PublishDir).  Properties are set from all top-level `<PropertyGroup />`s (those not in Targets) so if you set a property like $(OutputPath) in a target, you need to reset any properties that should contain its value.

Here is my example: https://github.com/jeffkl/MSBuild-NetCore/blob/master/src/OutputPathViaInlineTask/build.targets

Which is imported here: https://github.com/jeffkl/MSBuild-NetCore/blob/master/src/OutputPathViaInlineTask/OutputPathViaInlineTask.csproj#L24

My output looks correct:
```
D:\MSBuild-NetCore\src\OutputPathViaInlineTask>msbuild
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/31/2017 10:39:41 AM.
Project "D:\MSBuild-NetCore\src\OutputPathViaInlineTask\OutputPathViaInlineTask.csproj" on node 1 (default targets).
SetOutputPath:
  Before:
   OutputPath: ''
   OutDir: ''
   PublishDir: 'app.publish\'
   _InvalidConfigurationError: 'true'
   _InvalidConfigurationWarning: ''
  After:
   OutputPath: 'bin\b6db3d27980d4badbfa814fe19b32f83\'
   OutDir: 'bin\b6db3d27980d4badbfa814fe19b32f83\'
   PublishDir: 'bin\b6db3d27980d4badbfa814fe19b32f83\app.publish\'
   _InvalidConfigurationError: 'false'
   _InvalidConfigurationWarning: 'false'
PrepareForBuild:
  Creating directory "bin\b6db3d27980d4badbfa814fe19b32f83\".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /highentropyva+ /reference:"C:\Program
  Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Frame
  work\.NETFramework\v4.6\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll" /debug+ /
  out:obj\Debug\OutputPathViaInlineTask.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRe
  commendedRules.ruleset" /subsystemversion:6.00 /target:exe /utf8output Program.cs Properties\AssemblyInfo.cs "C:\Users\jeffkl\AppData\Local\Temp\.NETFramewor
  k,Version=v4.6.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\MSBuild\14.0\bin
_CopyAppConfigFile:
  Copying file from "App.config" to "bin\b6db3d27980d4badbfa814fe19b32f83\OutputPathViaInlineTask.exe.config".
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\OutputPathViaInlineTask.exe" to "bin\b6db3d27980d4badbfa814fe19b32f83\OutputPathViaInlineTask.exe".
  OutputPathViaInlineTask -> D:\MSBuild-NetCore\src\OutputPathViaInlineTask\bin\b6db3d27980d4badbfa814fe19b32f83\OutputPathViaInlineTask.exe
  Copying file from "obj\Debug\OutputPathViaInlineTask.pdb" to "OutputPathViaInlineTask.pdb".
Done Building Project "D:\MSBuild-NetCore\src\OutputPathViaInlineTask\OutputPathViaInlineTask.csproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.35
```

**Comment by am11** [comment]
@jeffkl, thank you so much, it worked! 🎉 👍 🍰

One related question regarding the `IntermediateOutputPath`:

If we take the same approach to override `IntermediateOutputPath`, then we need to change `IntermediateAssembly` which is defined in an `ItemGroup` in `Microsoft.CurrentVersion.Common.targets` file. If we `Include` the updated `IntermediateOutputPath` t `IntermediateAssembly`,  it gives error:

> error MSB4115: The "exists" function only accepts a scalar value, but its argument "@(IntermediateAssembly)" evaluates to "obj\Debug\LibSass.NET.dll;C:\Repos\libsass-net\LibSass.NET\Some_Computed_String_by_Inline_Task\obj\Debug\LibSass.NET.dll

If we `Remove` or `Exclude` the existing `@(IntermediateAssembly)`, it gives the error:

> error MSB4066: The attribute "Remove" in element <IntermediateAssembly> is unrecognized.

since it is defined in a different target and there is [a limitation](https://msdn.microsoft.com/en-us/library/ms164283.aspx) on both of these properties:

> This attribute is valid only if it's specified for an item in an ItemGroup that's in a Target.

Can we safely say that it is impossible to override `IntermediateOutputPath` from an inline task; or is there any workaround for it as well? :)

**Comment by jeffkl** [comment]
`IntermediateOutputPath` is a lot trickier because there are a bunch of items and properties that use it at the top-level.  You'd need to remove each item first before calling your inline task:

```xml
<ItemGroup>
  <IntermediateAssembly Remove="$(IntermediateOutputPath)$(TargetName)$(TargetExt)" />
</ItemGroup>
```

Then add them back after you've changed `IntermediateOutputPath`:

``` xml
<ItemGroup>
  <IntermediateAssembly Include="$(IntermediateOutputPath)$(TargetName)$(TargetExt)" />
</ItemGroup>
```

I see a bunch of items like `ApplicationManifest`, `_DeploymentManifestEntryPoint`, and `DeployManifest` that you'll have to reset.  Also there are properties like `_GenerateBindingRedirectsIntermediateAppConfig` which will be need to reset.

Its unfortunate that some properties are set before targets start executing, it really makes it hard to accomplish what you're going for...

**Comment by am11** [comment]
@jeffkl, I tried with:

```xml
<ItemGroup>
  <IntermediateAssembly Remove="$(IntermediateOutputPath)$(TargetName)$(TargetExt)" />
</ItemGroup>
```

in `csproj` file before and after `<Import>`'ing my `targets` file that has task, as well as by putting it in `targets` file before `<UsingTask>`, but `MSBuild 14.0` is throw the same error:

>error MSB4066: The attribute "Remove" in element `<IntermediateAssembly>` is unrecognized.

**Comment by jeffkl** [comment]
You have to do the remove within your target.  So do the removes here: https://github.com/jeffkl/MSBuild-NetCore/blob/master/src/OutputPathViaInlineTask/build.targets#L26

Then determine IntermediateOutputPath, and add back `IntermediateAssembly` here: https://github.com/jeffkl/MSBuild-NetCore/blob/master/src/OutputPathViaInlineTask/build.targets#L53

**Comment by am11** [comment]
WOW, that was probably the only combination I didn't try. 😄 Thank you soo very much @jeffkl! It worked! ⭐️ 🎉 🎈

I read your reply from phone, and was doubting (sorry 😊) that it will waive the `MSB4066` error, just tried on workstation and voila!

I have added the SO answer mentioning you and this post: http://stackoverflow.com/a/41967758/863980, so others who are stuck could also profit from this thread. 😸

Cheers and thanks again! 💯  👍

**Comment by dcby** [comment]
Any chance to do the same with version related properties (Version, VersionPrefix and VersionSuffix)? I can't find a way of how to set it from the task.

**Comment by dcby** [comment]
Disregard. Got it. As stated above
> you might need to set it and re-set any properties that have already been set with its value

So I need to set all properties that depends on changed property (VersionSuffix in my case). Sample:
```xml
<Target Name="CommitHash">
  <Exec Command="git rev-parse --short head" ConsoleToMSBuild="true" EchoOff="true">
    <Output TaskParameter="ConsoleOutput" PropertyName="CommitHash" />
  </Exec>

  <PropertyGroup>
    <VersionSuffix>$(CommitHash)</VersionSuffix>
    <!-- set Version as well!!! -->
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
  </PropertyGroup>
    
  <Warning Text="Version: $(Version)" />
</Target>
```

**Comment by h0st1le** [comment]
Doesn't seem to work when using Visual Studio 2017 and MSBuild15. Attempts to start and debug result in a proper compile but Visual Studio still seems to think that the output path to start the executable is at the old location.  Thus an error "Visual Studio cannot start debugging because the debug target is missing. Please build the project to retry. or set the OutputPath etc." I Looked for other properties that could influence this but havent had any luck.
